- name: Shell Commands
  hosts: all
  tasks:
    - name: uname CMD
      shell:
        "uname -a"
      register: unameoutput
      tag: unameoutput

    - name: Command output display
      debug:
        msg="{{unameoutput.stdout}}"
